// WhichForms Seed Data
// Comprehensive government forms explained in plain English

module.exports = {
  // ============ IDENTITY DOCUMENTS ============
  identityDocs: [
    {
      slug: 'social-security-card',
      name: 'Social Security Card',
      category: 'federal-identity',
      description: 'The Social Security card is your official proof of Social Security number. You need it for employment, taxes, and many government services.',
      plain_english: 'Think of your Social Security number (SSN) as your lifelong ID number for the US government. The card proves you have this number. Your SSN follows you from birth until death.',
      who_needs_it: 'Everyone who works in the US needs a Social Security card. Newborns, immigrants, and anyone who never got a card should apply.',
      required_documents: ['SS-5 form', 'Birth certificate or passport', 'Proof of citizenship or immigration status', 'Parent ID if applying for a child'],
      processing_time: '10-14 business days if applying by mail, same-day at SSA office',
      cost: 'Free',
      renewal_period: 'Only replace if lost, stolen, or name changes',
      official_url: 'https://www.ssa.gov/ssnumber/',
      state_specific: false,
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Can I get my Social Security card the same day?', a: 'Yes, if you visit a Social Security office in person with all required documents, you can often get your card the same day.' },
        { q: 'How much does a replacement Social Security card cost?', a: 'It is completely free to get a replacement card. The SSA does not charge for this service.' },
        { q: 'Can I apply for my baby\\'s Social Security card at the hospital?', a: 'Some hospitals offer to file for the SSN card when you register the birth. Ask at your hospital\\'s birth registration desk.' },
        { q: 'What if I need my card immediately for a job?', a: 'You can often start working before you have the actual card, as long as you can provide your SSN to the employer within a certain timeframe.' },
      ],
    },
    {
      slug: 'passport',
      name: 'US Passport',
      category: 'travel-identity',
      description: 'A passport is your ticket to international travel. It proves you are a US citizen and allows entry into other countries.',
      plain_english: 'Your passport is like a global ID card. When you travel abroad, other countries need to know you are allowed to enter. The passport does that.',
      who_needs_it: 'Anyone traveling outside the US by air needs a passport. Some land and sea travel to certain countries also requires one.',
      required_documents: ['DS-11 form', 'Proof of US citizenship', 'Photo ID', 'Passport photo', 'Payment for fees'],
      processing_time: '6-8 weeks standard, 3 weeks expedited',
      cost: '$130 for adults, $100 for children under 16',
      renewal_period: '10 years for adults',
      official_url: 'https://travel.state.gov/content/travel/en/passports.html',
      state_specific: false,
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Can I renew my passport by mail?', a: 'Yes, if your previous passport is not damaged and you were over 16 when it was issued, you can use form DS-82 to renew by mail.' },
        { q: 'How long does it take to get a passport?', a: 'Standard processing is 6-8 weeks. Expedited processing (with extra fee) takes about 3 weeks. Some locations offer in-person service the same day.' },
        { q: 'Do children need their own passport?', a: 'Yes, every traveler including infants needs their own passport to fly internationally.' },
        { q: 'What if I need a passport urgently for a trip?', a: 'You can make an appointment at a passport agency for emergency service. You must have travel within 2 weeks and show proof of the trip.' },
      ],
    },
    {
      slug: 'real-id',
      name: 'REAL ID Driver\\'s License',
      category: 'domestic-identity',
      description: 'Starting May 2025, you need a REAL ID to board domestic flights and enter federal buildings. It\\'s an upgraded driver\\'s license.',
      plain_english: 'The government is upgrading driver\\'s licenses to be more secure. After May 7, 2025, you need a REAL ID to fly within the US or enter federal buildings like courthouses.',
      who_needs_it: 'Anyone who needs to fly domestically or enter federal buildings after May 2025. Most people should get one even if they don\\'t fly often.',
      required_documents: ['Proof of identity (birth certificate or passport)', 'Proof of Social Security number', 'Proof of residency', 'Proof of lawful status'],
      processing_time: 'Varies by state DMV, often same-day to 2 weeks',
      cost: 'Varies by state, similar to regular license renewal ($20-50)',
      renewal_period: 'Typically 4-8 years',
      official_url: 'https://www.dhs.gov/real-id',
      state_specific: true,
      states: ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What\\'s the difference between a regular license and a REAL ID?', a: 'A REAL ID has a star in the top corner and has additional security features. It proves you are who you say you are at a higher level.' },
        { q: 'Can I use my passport instead of a REAL ID for flights?', a: 'Yes! A valid US passport is one of the approved IDs for domestic flights.' },
        { q: 'Do I need to renew my current license to get a REAL ID?', a: 'Not necessarily. In many states, you can upgrade to a REAL ID at any time, even before your current license expires.' },
        { q: 'What happens if I don\\'t get a REAL ID by May 2025?', a: 'You won\\'t be able to board domestic flights or enter federal buildings with a standard driver\\'s license. You\\'d need a passport or other approved ID instead.' },
      ],
    },
    {
      slug: 'birth-certificate',
      name: 'Birth Certificate',
      category: 'vital-records',
      description: 'A birth certificate is your proof of where and when you were born. You need it for almost everything official.',
      plain_english: 'Your birth certificate is one of the most important documents you own. It proves you exist, where you were born, who your parents are, and when you were born. You need it for everything from getting a driver\\'s license to applying for a passport.',
      who_needs_it: 'Everyone should have a birth certificate. Newborns need one, and adults should keep theirs safe.',
      required_documents: ['Varies by state - typically application form, ID, fee'],
      processing_time: '2-4 weeks typically, can be expedited',
      cost: '$10-30 depending on the state',
      renewal_period: 'One-time document, keep it forever',
      official_url: 'https://www.cdc.gov/nchs/wonderers.html',
      state_specific: true,
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Where do I get a copy of my birth certificate?', a: 'From the vital records office in the state where you were born. Many states now offer online ordering.' },
        { q: 'How long does it take to get a birth certificate?', a: 'Standard processing is usually 2-4 weeks. Expedited options are often available for an additional fee.' },
        { q: 'Can I get a birth certificate for my child who was born abroad?', a: 'Yes, contact the US embassy or consulate in that country to get a Consular Report of Birth Abroad.' },
        { q: 'What if I was born in a different state than where I live now?', a: 'You still get the birth certificate from the state where you were born. Many states allow you to order it online or by mail.' },
      ],
    },
    {
      slug: 'work-authorization-card',
      name: 'Employment Authorization Document (EAD)',
      category: 'federal-identity',
      description: 'An EAD card proves you are allowed to work in the US. If you\\'re not a citizen or permanent resident, you need this to work legally.',
      plain_english: 'Think of the EAD as your work permit. If you are in the US on a visa that doesn\\'t automatically allow work, you need this card to prove employers you can legally work.',
      who_needs_it: 'Non-citizens who need permission to work in the US. This includes certain visa holders, asylum seekers, and people with pending green card applications.',
      required_documents: ['Form I-765', 'Copy of your immigration status documents', 'Photo ID', 'Fee payment'],
      processing_time: '2-7 months depending on case type',
      cost: '$520 for most applications, $470 if under 14',
      renewal_period: 'Varies by status, typically 1-2 years',
      official_url: 'https://www.uscis.gov/working-in-the-united-states',
      state_specific: false,
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Can I work while waiting for my EAD?', a: 'It depends on your situation. If you have a pending asylum application, you may have work authorization. Check with an immigration attorney.' },
        { q: 'How do I know if I\\'m eligible for an EAD?', a: 'Common reasons include having a pending green card application, being an asylum applicant, being a dependent of certain visa holders, or having Temporary Protected Status.' },
        { q: 'Can my employer apply for my EAD for me?', a: 'No, you must apply yourself using Form I-765. Your employer cannot file for you.' },
        { q: 'What if my EAD is about to expire but my status isn\\'t finalized?', a: 'You should file for renewal before your current EAD expires. Processing times can be long.' },
      ],
    },
  ],

  // ============ SITUATIONS ============
  situations: [
    {
      slug: 'starting-a-business',
      title: 'Starting a Business',
      description: 'Everything you need to officially start your business - from registering your company to getting an EIN.',
      plain_english: 'Starting a business means doing paperwork. You need to choose a business structure, register with the government, and get a tax ID number. The good news? Most of it can be done online.',
      category: 'business',
      search_volume_estimate: 'High',
      form_slugs: ['form-ss-4-ein', 'form-irs-8832-entity-classification', 'form-llc-operating-agreement', 'form-corporation-incorporation', 'form-dba-fictitious-name'],
      identity_doc_slugs: ['social-security-card'],
      faqs: [
        { q: 'Do I need a lawyer to start a business?', a: 'Not necessarily. Many small businesses can file their own paperwork using online services. However, complex situations (like multiple partners or liability concerns) may benefit from professional help.' },
        { q: 'Should I form an LLC or a corporation?', a: 'An LLC is often simpler and provides personal liability protection. A corporation has more rules but can be better for raising investment money. Most small businesses start with an LLC.' },
        { q: 'Do I need an EIN if I\\'m a sole proprietor?', a: 'Technically no, you can use your Social Security number. But getting an EIN keeps your business and personal finances separate, which is better for taxes and legal protection.' },
        { q: 'How long does it take to start a business?', a: 'You can often get your EIN in minutes online. Registering with your state can take 1-2 weeks. Getting all licenses and permits can take longer depending on your industry.' },
      ],
    },
    {
      slug: 'filing-taxes-as-an-individual',
      title: 'Filing Taxes as an Individual',
      description: 'Your annual tax return - what forms you need, when to file, and how to maximize your refund.',
      plain_english: 'Every year, most Americans have to tell the government how much money they made and pay taxes on it. This process is called filing your taxes. The good news? If you\\'re employed, your employer already takes out some taxes for you.',
      category: 'tax',
      search_volume_estimate: 'Very High',
      form_slugs: ['form-1040-us-individual-income-tax-return', 'form-w-4-employees-withholding', 'form-w-2-wage-statement', 'form-1099-misc-independent-contractor'],
      identity_doc_slugs: ['social-security-card'],
      faqs: [
        { q: 'Do I have to file taxes if I didn\\'t make much money?', a: 'It depends on your filing status and income. If you are single and made less than $14,600 in 2024, you might not owe anything. But you should still file to get any credits you qualify for.' },
        { q: 'What happens if I don\\'t file on time?', a: 'If you owe taxes and don\\'t file, you face penalties and interest. If you\\'re owed a refund, you have 3 years to claim it, but you lose money by waiting.' },
        { q: 'Should I take the standard deduction or itemize?', a: 'Most people take the standard deduction because it\\'s simpler. You only need to itemize if your deductible expenses (like mortgage interest or charity) add up to more than the standard deduction.' },
        { q: 'How do I know which tax forms I need?', a: 'If you are an employee with simple finances, you likely just need Form 1040. Self-employed people and those with significant investments, rental income, or other complications may need additional forms.' },
      ],
    },
    {
      slug: 'applying-for-a-green-card',
      title: 'Applying for a Green Card (Lawful Permanent Residence)',
      description: 'Your path to becoming a permanent resident of the United States.',
      plain_english: 'A green card means you can live and work in the US forever. It\\'s called a green card because of the color of the physical card they used to give out. The official name is Lawful Permanent Residence (LPR).',
      category: 'immigration',
      search_volume_estimate: 'High',
      form_slugs: ['form-i-485-adjustment-of-status', 'form-i-130-petition-for-relative', 'form-i-765-work-authorization', 'form-n-400-naturalization'],
      identity_doc_slugs: ['work-authorization-card', 'social-security-card'],
      faqs: [
        { q: 'How long does it take to get a green card?', a: 'It depends on your relationship to a US citizen or your employment situation. Family-based green cards can take 1-3 years. Employment-based can also take 1-3 years. For some categories, it can be much longer.' },
        { q: 'Can I work while waiting for my green card?', a: 'If you have a pending adjustment of status application and your EAD is approved, yes. You can apply for an EAD using Form I-765.' },
        { q: 'What\\'s the difference between a visa and a green card?', a: 'A visa is for temporary entry. A green card means permanent residence. With a visa, you have to leave eventually. With a green card, you can stay forever.' },
        { q: 'Can I lose my green card?', a: 'Yes. If you commit certain crimes, abandon your residence, or lie on your application, you can be placed in removal proceedings and lose your status.' },
      ],
    },
    {
      slug: 'becoming-a-us-citizen',
      title: 'Becoming a US Citizen (Naturalization)',
      description: 'The process of applying for US citizenship after being a permanent resident.',
      plain_english: 'Naturalization is how someone who was born in another country becomes a US citizen. After living in the US as a green card holder for a certain number of years, you can apply to become a citizen.',
      category: 'immigration',
      search_volume_estimate: 'High',
      form_slugs: ['form-n-400-application-for-naturalization', 'form-n-600-certificate-of-citizenship'],
      identity_doc_slugs: ['social-security-card', 'passport'],
      faqs: [
        { q: 'How long do I have to have a green card before applying for citizenship?', a: 'Generally 5 years as a permanent resident. If you\\'re married to a US citizen, it\\'s 3 years. Some categories like asylum holders have different rules.' },
        { q: 'What are the citizenship requirements?', a: 'You need to be 18+, have a green card for the required time, be able to read/write English, know US history and government, have good moral character, and pass the naturalization test.' },
        { q: 'What\\'s on the citizenship test?', a: 'An English test (reading, writing, speaking) and a civics test about US history and government. There are 100 possible civics questions, and you\\'ll be asked 10. You need to get 6 correct to pass.' },
        { q: 'Do I have to give up my original citizenship?', a: 'That depends on your home country. The US doesn\\'t require you to give up your original citizenship. Some countries (like Japan or India) may require you to choose one.' },
      ],
    },
    {
      slug: 'getting-a-driver-license',
      title: 'Getting a Driver\\'s License',
      description: 'How to get your first driver\\'s license or renew your existing one.',
      plain_english: 'A driver\\'s license lets you legally drive on public roads. Each state has its own DMV that issues licenses. You have to pass a written test and a driving test to get your first license.',
      category: 'identity',
      search_volume_estimate: 'Very High',
      form_slugs: ['form-driver-license-application'],
      identity_doc_slugs: ['real-id', 'social-security-card', 'birth-certificate'],
      faqs: [
        { q: 'What do I need to bring to the DMV?', a: 'Typically: proof of identity (birth certificate or passport), proof of Social Security number, and proof of residency in the state. For a REAL ID, you\\'ll need additional documents.' },
        { q: 'Can I drive with an out-of-state license?', a: 'Yes, for a limited time. Most states allow you to use a valid out-of-state license for 30-90 days after moving. After that, you need to get a new license from your new state.' },
        { q: 'What\\'s the difference between a driver\\'s license and a REAL ID?', a: 'Starting May 2025, a standard driver\\'s license won\\'t be valid for domestic flights or federal building access. A REAL ID has a star in the corner and meets federal security standards.' },
        { q: 'How do I renew my driver\\'s license?', a: 'Most states let you renew online, by mail, or in person. Check your state DMV website. Many states now require you to renew in person every few years for REAL ID compliance.' },
      ],
    },
    {
      slug: 'opening-a-bank-account',
      title: 'Opening a Business Bank Account',
      description: 'Why you need a separate business account and how to open one.',
      plain_english: 'Mixing personal and business money is one of the biggest mistakes new business owners make. A business bank account keeps everything separate, makes taxes easier, and makes your business look more professional.',
      category: 'business',
      search_volume_estimate: 'Medium',
      form_slugs: ['form-ss-4-ein'],
      identity_doc_slugs: ['social-security-card'],
      faqs: [
        { q: 'Can I use my personal checking account for my business?', a: 'Legally yes, but it\\'s not recommended. Mixing personal and business money makes accounting harder, creates liability issues, and can cause problems if you\\'re audited.' },
        { q: 'What do I need to open a business bank account?', a: 'Typically: EIN, business formation documents (LLC certificate, etc.), business license, and personal ID. Some banks may have additional requirements.' },
        { q: 'How long does it take to open a business account?', a: 'Usually 1-3 business days if you have all your documents ready. Some online banks can open accounts faster.' },
        { q: 'Do I need an EIN to open a business bank account?', a: 'Most banks require an EIN for a business account, even for sole proprietors. It\\'s free and easy to get one online from the IRS.' },
      ],
    },
    {
      slug: 'hiring-employees',
      title: 'Hiring Employees',
      description: 'The paperwork and requirements for legally hiring someone to work for your business.',
      plain_english: 'When you hire employees, you become responsible for payroll taxes, withholding, and various government forms. This is more complicated than being self-employed or hiring contractors.',
      category: 'business',
      search_volume_estimate: 'Medium',
      form_slugs: ['form-941-quarterly-federal-tax-return', 'form-i-9-employment-verification', 'form-w-4-employees-withholding', 'form-ul-1-state-unemployment'],
      identity_doc_slugs: ['social-security-card'],
      faqs: [
        { q: 'What forms do I need when hiring someone?', a: 'Form I-9 (verify they can work), Form W-4 (their tax withholding), and state new hire reporting. You\\'ll also need to register for payroll taxes.' },
        { q: 'What\\'s the difference between an employee and an independent contractor?', a: 'Employees work for you and you control how/when they work. Contractors choose their own methods. Misclassifying workers can result in penalties and back taxes.' },
        { q: 'How do payroll taxes work?', a: 'You withhold income tax and Social Security/Medicare from employee paychecks. You also pay the employer portion of Social Security and Medicare, plus federal unemployment tax.' },
        { q: 'Do I need to pay workers\\' compensation insurance?', a: 'Almost certainly yes, once you have employees. Requirements vary by state. This insurance protects you and your employees if someone gets hurt on the job.' },
      ],
    },
    {
      slug: 'filing-for-bankruptcy',
      title: 'Filing for Bankruptcy',
      description: 'When you can\\'t pay your debts, bankruptcy can give you a fresh start. Here\\'s what you need to know.',
      plain_english: 'Bankruptcy is a legal process that can help people who owe more money than they can pay. It\\'s not a failure - it\\'s a tool. Chapter 7 eliminates most debts. Chapter 13 creates a payment plan.',
      category: 'financial',
      search_volume_estimate: 'Medium',
      form_slugs: ['form-1060-chapter-7-bankruptcy', 'form-1065-chapter-13-reorganization'],
      identity_doc_slugs: ['social-security-card'],
      faqs: [
        { q: 'Will bankruptcy ruin my credit forever?', a: 'No. A Chapter 7 stays on your credit for 10 years, Chapter 13 for 7 years. But you can start rebuilding credit immediately after bankruptcy. Many people get credit cards within 1-2 years.' },
        { q: 'Can I keep my house and car if I file bankruptcy?', a: 'Usually yes, if you can continue making payments. In Chapter 13, you catch up missed payments over time. In Chapter 7, you can reaffirm the debt and keep making payments.' },
        { q: 'What debts can\\'t be erased in bankruptcy?', a: 'Student loans are rarely discharged. Child support, alimony, recent taxes, and debts from fraud can\\'t be eliminated either.' },
        { q: 'Do I need a lawyer to file bankruptcy?', a: 'Not required, but recommended for Chapter 13 which is more complex. Many people file Chapter 7 without a lawyer using form instructions.' },
      ],
    },
  ],

  // ============ IRS FORMS ============
  irsForms: [
    {
      slug: 'form-1040-us-individual-income-tax-return',
      form_number: '1040',
      name: 'US Individual Income Tax Return',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'The main tax form for individual Americans. Everyone with enough income files this annually.',
      plain_english: 'This is THE tax form. If you earn money in the US, you probably use this form to tell the government how much you made and pay your taxes. Think of it as your annual report to the IRS about your finances.',
      who_needs_it: 'Most Americans who earn above a certain threshold. Even if you don\\'t owe taxes, you should file to claim credits you qualify for.',
      deadline: 'April 15 each year (or next business day if weekend/holiday)',
      processing_time: '8-12 weeks for refunds if e-filed, up to 6 months if paper filed',
      official_url: 'https://www.irs.gov/forms-instructions',
      difficulty_level: 'Moderate',
      cost: 'Free if you file yourself',
      situations: ['filing-taxes-as-an-individual'],
      states: [],
      affiliate_type: 'turbotax',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What\\'s the difference between the 1040, 1040-SR, and 1040-NR?', a: '1040 is the standard form. 1040-SR is for seniors with larger print and simplified language. 1040-NR is for non-resident aliens.' },
        { q: 'Can I file my taxes for free?', a: 'Yes! The IRS offers Free File for those earning under $79,000. Many states also offer free state tax filing.' },
        { q: 'What happens if I can\\'t afford to pay what I owe?', a: 'File anyway! You can set up a payment plan with the IRS. The penalty for not filing is worse than the penalty for not paying.' },
        { q: 'How do I know if I should file a joint or separate return?', a: 'Most married couples benefit from filing jointly due to higher standard deductions and certain credits. But if one spouse has high medical expenses, separate filing might help.' },
      ],
    },
    {
      slug: 'form-w-4-employees-withholding',
      form_number: 'W-4',
      name: 'Employee\\'s Withholding Certificate',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Tell your employer how much tax to withhold from your paycheck.',
      plain_english: 'When you start a job, you fill out this form to tell your boss how much money to take out of each paycheck for taxes. Too much withheld = bigger refund. Too little withheld = you might owe money at tax time.',
      who_needs_it: 'Everyone starting a new job. Also fill out a new one when your life changes (marriage, new baby, buying a house).',
      deadline: 'Within first week of starting a job',
      processing_time: 'Immediate - affects next paycheck',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-w-4',
      difficulty_level: 'Easy',
      cost: 'Free',
      situations: ['filing-taxes-as-an-individual'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'How do I know how many allowances to claim?', a: 'The more allowances you claim, the less tax is withheld. Use the IRS withholding calculator at irs.gov/withholding for personalized advice based on your situation.' },
        { q: 'Should I claim 0 or 1 on my W-4?', a: 'Claiming 0 means maximum withholding (biggest refund). Claiming 1 is more typical. The right answer depends on your income, marital status, and whether you have dependents.' },
        { q: 'What if I don\\'t fill out a W-4?', a: 'Your employer must withhold at the highest rate (no allowances). This usually results in a large refund but less take-home pay throughout the year.' },
        { q: 'Can I change my W-4 after I start working?', a: 'Yes! You can submit a new W-4 anytime. It takes effect as soon as your employer processes it, usually within a pay period or two.' },
      ],
    },
    {
      slug: 'form-w-2-wage-statement',
      form_number: 'W-2',
      name: 'Wage and Tax Statement',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Your employer sends this to show how much you earned and taxes withheld.',
      plain_english: 'Think of this as your employer\\'s annual report to you (and the IRS) about your job. It shows how much money you made and how much tax was taken out of your paychecks.',
      who_needs_it: 'Every employee who earned wages during the year. Your employer must send it to you by January 31.',
      deadline: 'Employers must send to employees by January 31 for the previous year',
      processing_time: 'Provided annually',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-w-2',
      difficulty_level: 'Easy',
      cost: 'Free to receive - your employer prepares it',
      situations: ['filing-taxes-as-an-individual'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What if I don\\'t get my W-2 by mid-February?', a: 'Contact your employer first. If they can\\'t help, you can call the IRS at 800-829-1040. You may also need to file an extension or estimate your wages.' },
        { q: 'What\\'s the difference between Box 1 (Wages) and Box 3 (Social Security wages)?', a: 'Box 1 is your taxable wages after pre-tax deductions. Box 3 is your wages before deductions and is used to calculate Social Security benefits you\\'ll get later.' },
        { q: 'My W-2 shows federal tax withheld but I didn\\'t work the whole year. Is that right?', a: 'Yes, if you started mid-year. Your employer withholds based on your W-4 settings, not your expected annual income unless you filled out the step 2(c) multiple jobs worksheet.' },
        { q: 'Should I keep my W-2 forever?', a: 'Keep all tax documents for at least 3 years after you file (the IRS has 3 years to audit). Keep W-2s longer - they prove your work history for Social Security benefits.' },
      ],
    },
    {
      slug: 'form-1099-misc-independent-contractor',
      form_number: '1099-MISC',
      name: 'Miscellaneous Income',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Reports money you received as an independent contractor or from other sources.',
      plain_english: 'If you work for yourself (as a contractor, freelancer, or gig worker), businesses pay you and report it on this form. You\\'ll get one if you earned $600+ from any one client during the year.',
      who_needs_it: 'Independent contractors, freelancers, gig workers, and anyone who received payments not through regular employment.',
      deadline: 'Businesses must send to recipients by January 31; file with IRS by February 28 (paper) or March 31 (electronic)',
      processing_time: 'Provided annually',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-1099-misc',
      difficulty_level: 'Easy',
      cost: 'Free to receive',
      situations: ['filing-taxes-as-an-individual'],
      states: [],
      affiliate_type: 'turbotax',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Do I need to pay taxes on 1099 income?', a: 'Yes! 1099 income is not automatically taxed. You\\'re responsible for paying self-employment tax (Social Security and Medicare) plus income tax. Set aside about 25-30% for taxes.' },
        { q: 'What if I earned less than $600?', a: 'The company doesn\\'t have to send you a 1099, but you still must report the income on your tax return.' },
        { q: 'How do I deduct expenses on 1099 income?', a: 'You can deduct ordinary and necessary business expenses. Common ones include home office, equipment, software, and professional services. Keep receipts!' },
        { q: 'What if I didn\\'t get a 1099 but should have?', a: 'First, contact the payer to request it. If they won\\'t send it, report the income anyway based on your own records. The IRS gets a copy too.' },
      ],
    },
    {
      slug: 'form-1098-mortgage-interest-statement',
      form_number: '1098',
      name: 'Mortgage Interest Statement',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Reports the mortgage interest you paid during the year. Essential for itemizing deductions.',
      plain_english: 'Your mortgage company sends this to show how much interest you paid on your home loan. If you own a home and itemize deductions, this is your ticket to a bigger tax break.',
      who_needs_it: 'Homeowners who paid mortgage interest. You\\'ll receive it automatically from your mortgage servicer if you paid $600+ in interest.',
      deadline: 'Mortgage servicers must send by January 31',
      processing_time: 'Provided annually',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-1098',
      difficulty_level: 'Easy',
      cost: 'Free - sent by your mortgage company',
      situations: ['filing-taxes-as-an-individual'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'Is mortgage interest still deductible?', a: 'Yes, but with limits. You can deduct interest on up to $750,000 of mortgage debt (or $1 million for loans taken out before December 15, 2017).' },
        { q: 'What if I paid less than $600 in interest?', a: 'Your servicer doesn\\'t have to send you a 1098, but you can still deduct the interest. Keep your monthly statements as documentation.' },
        { q: 'Can I deduct points I paid on my mortgage?', a: 'Usually yes, but points on a refinanced loan must be deducted over the life of the loan, not all at once.' },
        { q: 'What\\'s on the 1098 besides interest?', a: 'It also shows real estate taxes your servicer paid from your escrow account, mortgage insurance premiums (which may be deductible), and any overpayment that was refunded.' },
      ],
    },
    {
      slug: 'form-ss-4-ein',
      form_number: 'SS-4',
      name: 'Application for Employer Identification Number',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Get your business\\'s tax ID number - essential for hiring, banking, and filing taxes.',
      plain_english: 'An EIN is like a Social Security number for your business. Banks want it to open accounts. Employees need it for their W-2s. The IRS needs it to track your business taxes. Best of all - it\\'s free and takes about 5 minutes online.',
      who_needs_it: 'Anyone starting a business with employees, forming an LLC, opening a business bank account, or filing business tax returns.',
      deadline: 'Before opening a business bank account or hiring employees',
      processing_time: 'Immediate online, 1-2 weeks by phone or mail',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-ss-4',
      difficulty_level: 'Easy',
      cost: 'Free',
      situations: ['starting-a-business', 'opening-a-bank-account', 'hiring-employees'],
      states: [],
      affiliate_type: 'legalzoom',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Do I need an EIN if I\\'m a sole proprietor with no employees?', a: 'Not technically, but it\\'s recommended. An EIN keeps your business and personal finances separate, which is important for taxes and liability.' },
        { q: 'How do I apply for an EIN?', a: 'The fastest way is online at irs.gov. Have your Social Security number, business name, and address ready. Takes about 15 minutes.' },
        { q: 'Can I use my personal SSN instead of an EIN?', a: 'Sole proprietors without employees can use their SSN, but this isn\\'t recommended. An EIN is better for privacy and professional appearance.' },
        { q: 'What if I lose my EIN?', a: 'Search your email for the IRS confirmation, check any previous tax filings, or call the IRS Business & Specialty Tax line at 800-829-4933.' },
      ],
    },
    {
      slug: 'form-irs-8832-entity-classification',
      form_number: '8832',
      name: 'Entity Classification Election',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Choose how your business will be taxed - as a partnership, corporation, or disregarded entity.',
      plain_english: 'When you form an LLC, you have to tell the IRS how you want to be taxed. Most single-member LLCs are \"disregarded\" (they don\\'t file their own tax return). Multi-member LLCs are usually partnerships. But you can choose differently if you want.',
      who_needs_it: 'LLC owners who want to be taxed as a corporation (C-corp or S-corp) instead of the default partnership or disregarded entity treatment.',
      deadline: 'Generally within 75 days of forming the LLC to take effect immediately, or at any time to take effect in future years',
      processing_time: '4-8 weeks',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-8832',
      difficulty_level: 'Moderate',
      cost: 'Free',
      situations: ['starting-a-business'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'What\\'s the difference between default and elected tax treatment?', a: 'Default for single-member LLCs is no business tax return (income flows through to personal return). You can elect to be taxed as an S-corp to potentially save on self-employment tax.' },
        { q: 'Can I change my election later?', a: 'Yes, but generally you must wait 5 years before making the same election again. There are exceptions for significant changes in business structure.' },
        { q: 'What\\'s an S-corp election and why would I want one?', a: 'An S-corp can save money on self-employment tax. Instead of paying SE tax on all profits, you pay yourself a reasonable salary (taxed as employment) and the rest as distributions (not taxed as SE).' },
        { q: 'Does this affect my state taxes?', a: 'Federal and state entity classification are separate. Most states follow federal treatment, but some have different rules. Check with your state.' },
      ],
    },
    {
      slug: 'form-941-quarterly-federal-tax-return',
      form_number: '941',
      name: 'Employer\\'s Quarterly Federal Tax Return',
      agency: 'IRS',
      agency_slug: 'irs',
      description: 'Report payroll taxes you withheld from employees and employer taxes you owe.',
      plain_english: 'Every quarter, businesses with employees tell the IRS how much they withheld from employees for income tax and Social Security/Medicare, plus the employer\\'s share of those taxes.',
      who_needs_it: 'Any business with employees. Even one employee counts.',
      deadline: 'April 30, July 31, October 31, January 31 for the previous quarter',
      processing_time: 'Varies by filing method',
      official_url: 'https://www.irs.gov/forms-pubs/about-form-941',
      difficulty_level: 'Moderate',
      cost: 'Free to file',
      situations: ['hiring-employees'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'What happens if I miss a quarterly filing deadline?', a: 'You may face penalties that increase the longer you wait. File even if you can\\'t pay - the penalty for late filing is worse than the penalty for late payment.' },
        { q: 'Can I file 941 electronically?', a: 'Yes, using IRS e-file or a third-party payroll service. E-filing is faster and reduces errors.' },
        { q: 'What if I have no employees in a quarter?', a: 'You still need to file (or can file a final return if you\\'ve terminated all employees). Filing zero wages is different from not filing.' },
        { q: 'When are payroll tax deposits due?', a: 'Monthly or semi-weekly depending on your tax liability. The IRS will notify you of your deposit schedule when you get your EIN.' },
      ],
    },
  ],

  // ============ USCIS FORMS ============
  uscisForms: [
    {
      slug: 'form-i-485-adjustment-of-status',
      form_number: 'I-485',
      name: 'Application to Register Permanent Residence or Adjust Status',
      agency: 'USCIS',
      agency_slug: 'uscis',
      description: 'The main form to apply for a green card from within the United States.',
      plain_english: 'This is THE green card application. If you\\'re already in the US and want to become a permanent resident, this is how you do it. It\\'s a long form with lots of supporting documents, but it\\'s the gateway to living in the US forever.',
      who_needs_it: 'People already in the US who want to become permanent residents. This includes those with family petitions, employment-based immigrants, and asylum holders.',
      deadline: 'When your priority date becomes current (varies by category)',
      processing_time: '8-24 months depending on your category and location',
      official_url: 'https://www.uscis.gov/i-485',
      difficulty_level: 'Complex',
      cost: '$1,440 plus $85 biometric fee for most applicants',
      situations: ['applying-for-a-green-card'],
      states: [],
      affiliate_type: 'boundless',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Can I work while my I-485 is pending?', a: 'Yes, if you have an Employment Authorization Document (EAD). Apply for it using Form I-765 either with your I-485 or separately.' },
        { q: 'Can I travel while my I-485 is pending?', a: 'Generally yes, but leaving the US can affect your application if you\\'ve been out of status. Get advance parole (Form I-131) before traveling.' },
        { q: 'What\\'s an adjustment of status interview?', a: 'Most applicants have an interview at a USCIS office where they verify documents and answer questions under oath about their application.' },
        { q: 'How do I know if my I-485 is approved?', a: 'USCIS will send an approval notice. You\\'ll also receive your green card in the mail within a few weeks after approval.' },
      ],
    },
    {
      slug: 'form-i-130-petition-for-relative',
      form_number: 'I-130',
      name: 'Petition for Alien Relative',
      agency: 'USCIS',
      agency_slug: 'uscis',
      description: 'Start the green card process by establishing your family relationship to a US citizen or permanent resident.',
      plain_english: 'Before your family member can apply for a green card, someone has to prove they\\'re related to a US citizen or permanent resident. That\\'s what this form does. Think of it as the first domino - it must fall before anything else can happen.',
      who_needs_it: 'US citizens or permanent residents who want to help a family member get a green card.',
      deadline: 'File whenever you\\'re ready (but processing times are long)',
      processing_time: '6-18 months depending on your location and relationship type',
      official_url: 'https://www.uscis.gov/i-130',
      difficulty_level: 'Moderate',
      cost: '$535 for most categories plus possible $120 potential fees',
      situations: ['applying-for-a-green-card'],
      states: [],
      affiliate_type: 'boundless',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Who can I petition for?', a: 'US citizens can petition for spouses, children, parents, and siblings. Permanent residents can petition for spouses and children only.' },
        { q: 'Can I file I-130 and I-485 at the same time?', a: 'If you\\'re a US citizen and your relative is in the US legally with a visa that\\'s current, you can file concurrently. Otherwise, the relative must wait for the I-130 to be approved first.' },
        { q: 'What\\'s the difference between immediate relatives and family preference?', a: 'Immediate relatives (spouses, unmarried children under 21, parents of US citizens) have unlimited visa availability. Family preference categories have annual limits, causing long waits.' },
        { q: 'Can I expedite my I-130?', a: 'Only in limited circumstances: severe financial hardship to the petitioner, military service, or compelling humanitarian factors. USCIS reviews expedite requests case-by-case.' },
      ],
    },
    {
      slug: 'form-i-765-work-authorization',
      form_number: 'I-765',
      name: 'Application for Employment Authorization',
      agency: 'USCIS',
      agency_slug: 'uscis',
      description: 'Apply for permission to work in the United States if you\\'re not automatically authorized.',
      plain_english: 'Not everyone can work in the US just because they\\'re here. If you\\'re here on certain visas or have a pending green card application, you need this card that says you\\'re allowed to work. It\\'s called an EAD (Employment Authorization Document).',
      who_needs_it: 'Non-citizens who need permission to work. Common reasons include pending green card applications, certain student visas, asylum seekers, and people with temporary protected status.',
      deadline: 'Can file at same time as I-485 or separately',
      processing_time: '2-7 months depending on category',
      official_url: 'https://www.uscis.gov/i-765',
      difficulty_level: 'Moderate',
      cost: '$520 for most applications, $470 if under 14',
      situations: ['applying-for-a-green-card'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Can I work while waiting for my EAD?', a: 'It depends. If your EAD application is pending and you fall into certain categories (like pending asylum application), you may have work authorization. Check with an immigration attorney.' },
        { q: 'Is the EAD the same as a green card?', a: 'No. The EAD only allows you to work. A green card (permanent residence) allows you to live and work permanently. The EAD is temporary and tied to your immigration status.' },
        { q: 'What\\'s the 180-day rule?', a: 'If you have a pending EAD renewal and file before it expires, you can keep working for up to 180 days past the expiration date while waiting for the new one.' },
        { q: 'Can my employer help me get an EAD?', a: 'No. You must file for yourself. Your employer can\\'t file on your behalf, though they may be able to help with processing timing.' },
      ],
    },
    {
      slug: 'form-n-400-naturalization',
      form_number: 'N-400',
      name: 'Application for Naturalization',
      agency: 'USCIS',
      agency_slug: 'uscis',
      description: 'Apply to become a US citizen after being a permanent resident.',
      plain_english: 'This form starts the process of becoming an American citizen. If you\\'ve been a green card holder for long enough and meet the requirements, filling this out is your path to voting, holding a US passport, and never worrying about losing your immigration status.',
      who_needs_it: 'Green card holders who have lived in the US long enough (usually 5 years, or 3 years if married to a US citizen) and meet all other requirements.',
      deadline: 'After meeting the 3 or 5 year residence requirement plus 3 months continuous residence in the same state',
      processing_time: '10-18 months from filing to oath ceremony',
      official_url: 'https://www.uscis.gov/n-400',
      difficulty_level: 'Moderate',
      cost: '$725 ($640 + $85 biometric fee)',
      situations: ['becoming-a-us-citizen'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Do I have to be good at English to become a citizen?', a: 'You need to speak, read, and write basic English. There are exceptions for people over 50 who have been permanent residents for 20+ years, or over 55 with 15+ years.' },
        { q: 'What\\'s on the civics test?', a: 'You\\'ll be asked 10 questions from a list of 100. You need to get at least 6 correct. Topics include American history, government, and geography. Study materials are available on the USCIS website.' },
        { q: 'Can I apply for citizenship if I have a criminal record?', a: 'It depends on the crime. Some convictions make you permanently ineligible, others may be overcome with time and evidence of rehabilitation. Consult an immigration attorney.' },
        { q: 'What happens at the oath ceremony?', a: 'You\\'ll take the Oath of Allegiance to the United States, surrender your green card, and receive your Certificate of Naturalization. This is the final step!' },
      ],
    },
    {
      slug: 'form-i-9-employment-verification',
      form_number: 'I-9',
      name: 'Employment Eligibility Verification',
      agency: 'USCIS',
      agency_slug: 'uscis',
      description: 'Verify that every employee is legally allowed to work in the United States.',
      plain_english: 'Every time someone gets hired in the US, their employer must check that they\\'re allowed to work here. The employee brings documents (like a passport or Social Security card) and the employer fills out this form to prove they did their homework.',
      who_needs_it: 'Employers hiring workers in the US. Everyone gets verified, not just immigrants - even US citizens need to show their documents.',
      deadline: 'Within 3 days of start of employment',
      processing_time: 'Done at time of hire',
      official_url: 'https://www.uscis.gov/i-9',
      difficulty_level: 'Easy',
      cost: 'Free - employer completes it',
      situations: ['hiring-employees'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What documents can employees show?', a: 'The form lists acceptable documents in three categories: List A (proves identity and work authorization together like a passport), List B (identity only - need also List C for work auth), or combinations.' },
        { q: 'Can I accept a copy of a document?', a: 'For electronic or photocopy records, you can accept them only if you\\'re enrolled in E-Verify. Otherwise, you must examine the original documents in person.' },
        { q: 'What if an employee has pending immigration paperwork?', a: 'They can show their EAD (Employment Authorization Document) or even a pending I-485 receipt as proof of work authorization. All documents must be unexpired.' },
        { q: 'How long do I keep I-9 forms?', a: 'Keep for 3 years after the date of hire, or 1 year after employment ends, whichever is later. Retain these records even after an employee leaves.' },
      ],
    },
  ],

  // ============ SSA FORMS ============
  ssaForms: [
    {
      slug: 'form-ss-5-application-for-social-security-card',
      form_number: 'SS-5',
      name: 'Application for a Social Security Card',
      agency: 'Social Security Administration',
      agency_slug: 'ssa',
      description: 'Apply for your original Social Security card, a replacement, or to correct information.',
      plain_english: 'Your Social Security number is your lifetime ID for the US government. The card proves you have this number. You need it for jobs, taxes, banking, and almost every major life event.',
      who_needs_it: 'Everyone who works in the US, immigrants getting their first SSN, people who lost their card, and anyone who needs to update their information.',
      deadline: 'Apply before starting your first job or whenever you need the card',
      processing_time: 'Same day at SSA office, 10-14 days by mail',
      official_url: 'https://www.ssa.gov/ssnumber/',
      difficulty_level: 'Easy',
      cost: 'Free',
      situations: ['starting-a-business', 'opening-a-bank-account'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What documents do I need?', a: 'For a US-born adult: birth certificate and ID (driver\\'s license or passport). For immigrants: proof of immigration status and work authorization. All documents must be originals.' },
        { q: 'Can I get my card the same day?', a: 'Yes, if you visit a Social Security office in person with proper documentation. Many offices require appointments, so call ahead.' },
        { q: 'How many times can I replace my card?', a: 'There\\'s no limit for replacements due to legitimate reasons. However, SSA may require you to prove your identity every few replacements.' },
        { q: 'Can I apply for my child\\'s card?', a: 'Parents or guardians can apply for children under 18. You\\'ll need the child\\'s birth certificate and your own ID.' },
      ],
    },
    {
      slug: 'form-ssa-8000-application-for-social-security-benefits',
      form_number: 'SSA-8000',
      name: 'Application for Social Security Benefits',
      agency: 'Social Security Administration',
      agency_slug: 'ssa',
      description: 'Apply for retirement, disability, or Medicare benefits from Social Security.',
      plain_english: 'Social Security is basically a pension system the government runs. If you\\'ve worked and paid into it, you get money back when you retire, become disabled, or turn 65 for Medicare. This form starts that process.',
      who_needs_it: 'People who want to claim Social Security retirement benefits (usually at 62+), disability benefits, or Medicare coverage.',
      deadline: 'File 3 months before you want benefits to start',
      processing_time: '3-6 months for disability, faster for retirement',
      official_url: 'https://www.ssa.gov/benefits/retirement/',
      difficulty_level: 'Moderate',
      cost: 'Free',
      situations: [],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'When should I file for Social Security retirement?', a: 'You can file as early as 62, but waiting until 70 gives you the maximum benefit. The best age depends on your health, financial needs, and whether you\\'re still working.' },
        { q: 'How much will I get?', a: 'Your benefit is based on your 35 highest-earning years of work. Use the SSA\\'s online calculator at ssa.gov to estimate your benefit.' },
        { q: 'Can I work while receiving benefits?', a: 'Yes, but if you\\'re under full retirement age, benefits are reduced if you earn above a certain amount. After full retirement age, you can earn as much as you want.' },
        { q: 'What\\'s the difference between SSDI and SSI?', a: 'SSDI (Social Security Disability Insurance) requires you to have worked and paid into Social Security. SSI (Supplemental Security Income) is needs-based and for people with little or no work history.' },
      ],
    },
  ],

  // ============ BUSINESS FORMS ============
  businessForms: [
    {
      slug: 'form-llc-operating-agreement',
      form_number: 'LLC-001',
      name: 'LLC Operating Agreement',
      agency: 'Secretary of State',
      agency_slug: 'state-sos',
      description: 'The internal rulebook for your LLC - who owns what, how decisions are made, and what happens if someone wants out.',
      plain_english: 'An operating agreement is like a prenup for your business partners. It spells out who owns what percentage, how profits are split, who makes decisions, and what happens if someone wants to leave. Even single-member LLCs should have one.',
      who_needs_it: 'All LLC owners. While many states don\\'t require it, having one protects you and clarifies your business structure.',
      deadline: 'Before opening bank accounts or making business decisions',
      processing_time: 'Create it yourself or use an online service',
      official_url: 'https://www.legalzoom.com',
      difficulty_level: 'Easy to Moderate',
      cost: 'Free to create yourself, $50-200 through a service',
      situations: ['starting-a-business'],
      states: [],
      affiliate_type: 'legalzoom',
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'Do I need a lawyer to create an operating agreement?', a: 'Not necessarily. For simple single-member LLCs or straightforward multi-member LLCs, online templates and services work fine. Complex situations benefit from professional help.' },
        { q: 'What\\'s the difference between an operating agreement and articles of organization?', a: 'Articles of organization are filed with the state and contain basic info (name, address, registered agent). The operating agreement is internal and covers rules, ownership percentages, etc.' },
        { q: 'Can I change the operating agreement later?', a: 'Yes! Operating agreements can be amended. Usually, members vote on changes, and the amendment is documented in writing.' },
        { q: 'Do I have to file the operating agreement with the state?', a: 'No. The operating agreement stays private between LLC members. Only the articles of organization are public.' },
      ],
    },
    {
      slug: 'form-corporation-incorporation',
      form_number: 'INC-001',
      name: 'Articles of Incorporation',
      agency: 'Secretary of State',
      agency_slug: 'state-sos',
      description: 'The official document that creates your corporation with the state.',
      plain_english: 'When you form a corporation, you need to file these \"articles\" with your state. They\\'re like the birth certificate of your corporation - they officially bring it into existence.',
      who_needs_it: 'Anyone forming a corporation (C-corp or S-corp). Different from LLC filing.',
      deadline: 'File before starting business operations',
      processing_time: '1 day to 2 weeks depending on state and filing method',
      official_url: 'Varies by state',
      difficulty_level: 'Easy',
      cost: '$50-500 depending on state',
      situations: ['starting-a-business'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'What\\'s the difference between incorporating and forming an LLC?', a: 'Corporations have shareholders, directors, and officers with more formal structure. LLCs have members with more flexibility. Corporations can raise investment capital more easily.' },
        { q: 'What\\'s an S-corp election?', a: 'After incorporating, you can elect S-corp status with the IRS (Form 2553). S-corps avoid double taxation but have restrictions on who can be a shareholder.' },
        { q: 'Do I need a registered agent?', a: 'Yes, all corporations must have a registered agent - a person or company that accepts legal mail on behalf of the corporation. This is usually someone in the state where you incorporate.' },
        { q: 'What\\'s the difference between incorporating in Delaware vs. my home state?', a: 'Delaware has business-friendly laws and a specialized court system. But you still need to register to do business in your home state. Most small businesses should incorporate in their home state.' },
      ],
    },
    {
      slug: 'form-dba-fictitious-name',
      form_number: 'DBA-001',
      name: 'Fictitious Name / \"Doing Business As\" Registration',
      agency: 'County Clerk or Secretary of State',
      agency_slug: 'state-sos',
      description: 'Register a business name different from your legal company name.',
      plain_english: 'If you want to do business as \"Joe\\'s Plumbing\" but your company is legally \"Joseph Smith LLC,\" you need to file a DBA. It tells the world that these two names are the same business.',
      who_needs_it: 'Any business operating under a name different from its legal name. Sole proprietors using a business name, LLCs using a different \"fictitious\" name.',
      deadline: 'Before using the name in business',
      processing_time: '1 day to 4 weeks depending on jurisdiction',
      official_url: 'Varies by county/state',
      difficulty_level: 'Easy',
      cost: '$10-100 depending on jurisdiction',
      situations: ['starting-a-business'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'Why do I need to register a DBA?', a: 'It protects consumers who need to know who they\\'re doing business with, and it establishes your right to use that name in your area.' },
        { q: 'Does a DBA give me trademark protection?', a: 'No. A DBA only registers your local business name. To get trademark protection, you need to file with the USPTO. A DBA does NOT give you exclusive rights to the name.' },
        { q: 'How long is a DBA valid?', a: 'It varies by state. Some last 5 years, some are perpetual but require renewal. Check with your local filing office.' },
        { q: 'Can I open a bank account with just a DBA?', a: 'Banks usually want to see your formation documents (LLC paperwork, etc.) plus the DBA filing. The DBA alone typically isn\\'t enough.' },
      ],
    },
    {
      slug: 'form-ul-1-state-unemployment',
      form_number: 'UL-1',
      name: 'State Unemployment Insurance Registration',
      agency: 'State Employment Commission',
      agency_slug: 'state-sos',
      description: 'Register with your state to pay unemployment insurance taxes for employees.',
      plain_english: 'Unemployment insurance is money that helps people who lose their jobs. As an employer, you pay into this system. Most states require you to register before hiring your first employee.',
      who_needs_it: 'Any business hiring employees. Even one employee usually requires registration.',
      deadline: 'Within a certain period of hiring your first employee (varies by state)',
      processing_time: '1-2 weeks',
      official_url: 'Varies by state',
      difficulty_level: 'Easy',
      cost: 'Varies by state - based on payroll',
      situations: ['hiring-employees'],
      states: [],
      is_featured: false,
      is_published: true,
      faqs: [
        { q: 'How is unemployment tax calculated?', a: 'Each state has its own formula based on your payroll and your \"experience rating\" - basically, how many former employees have claimed unemployment from you.' },
        { q: 'Do I have to pay unemployment tax on all employees?', a: 'There\\'s usually a minimum threshold (like $1,000 in wages or one employee working 20+ weeks). Below that threshold, you might not owe yet.' },
        { q: 'What\\'s the difference between federal and state unemployment tax?', a: 'Federal unemployment (FUTA) is 6% on the first $7,000 of wages but reduced to 0.6% if you pay state unemployment on time. State unemployment varies by state.' },
        { q: 'Can I recover overpaid unemployment taxes?', a: 'In some states yes, through merit ratings or adjustments. In others, overpayments become part of your tax rate. Check your state\\'s rules.' },
      ],
    },
    {
      slug: 'form-driver-license-application',
      form_number: 'DL-001',
      name: 'Driver License Application',
      agency: 'Department of Motor Vehicles',
      agency_slug: 'dmv',
      description: 'Apply for your first driver\\'s license or renew your existing one.',
      plain_english: 'A driver\\'s license proves you can legally drive. Each state has its own DMV that issues them. You usually need to pass a written test, a driving test, and a vision test.',
      who_needs_it: 'Anyone who wants to legally drive. New drivers, people moving to a new state, and people renewing expired licenses.',
      deadline: 'Varies by state - usually within 30-90 days of moving',
      processing_time: 'Same day if you pass all tests',
      official_url: 'Varies by state - check your state DMV',
      difficulty_level: 'Moderate',
      cost: '$20-80 depending on state',
      situations: ['getting-a-driver-license'],
      states: [],
      is_featured: true,
      is_published: true,
      faqs: [
        { q: 'What tests do I need to take?', a: 'Usually: vision test (can you see?), written test (do you know the rules?), and driving test (can you actually drive?). Some states combine the written and driving portion.' },
        { q: 'Can I use my out-of-state license while waiting for my new one?', a: 'Yes, for a limited time after moving. Most states give you 30-90 days to get a new license. After that, you must have a license from that state.' },
        { q: 'What\\'s a REAL ID and do I need one?', a: 'Starting May 2025, a REAL ID is required for domestic flights and federal building access. It has a star in the corner. Most people should get one.' },
        { q: 'Can I renew my license online?', a: 'Many states allow online renewal, but you may need to visit a DMV in person periodically (often every 8 years) for identity verification.' },
      ],
    },
  ],
};